#!/bin/bash

echo opensrf...
#sudo -u opensrf env PATH... osrf_control -l --stop-all && sleep 2
#sudo -u opensrf env PATH... osrf_control -l --restart-all && sleep 2
sudo -u opensrf env PATH=${PATH}:/openils/bin /openils/bin/osrf_control -l --restart-all && sleep 2
echo opensrf...done

echo websocketd-osrf...
sudo systemctl stop websocketd-osrf && sleep 1
sudo systemctl start websocketd-osrf
echo websocketd-osrf...done

echo apache2...
sudo systemctl restart apache2
echo apache2...done
